### ISSUE TITLE
设置setLoadMoreEnabled(false)报空指针

### ISSUE THREAD

**Issue by Hellozhongxin** [jdsjlzx/LRecyclerView#100]
日志：
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter.getFooterViewsCount()' on a null object reference
                                                                           at com.github.jdsjlzx.recyclerview.LRecyclerView.setLoadMoreEnabled(LRecyclerView.java:365)
                                                                           at com.weili.bigbosscard.fragment.SecondCategoryItemFragment.intiUI(SecondCategoryItemFragment.java:98)
                                                                           at com.weili.bigbosscard.fragment.SecondCategoryItemFragment.onCreateView(SecondCategoryItemFragment.java:80)

我的设置代码是：
  rv = (LRecyclerView) layout.findViewById(R.id.rv);
        rv.setLayoutManager(new LinearLayoutManager(getContext()));
        rv.setRefreshProgressStyle(ProgressStyle.LineSpinFadeLoader);
        rv.setArrowImageView(R.drawable.ic_pulltorefresh_arrow);
        rv.setLoadingMoreProgressStyle(ProgressStyle.BallSpinFadeLoader);
//
        rv.setPullRefreshEnabled(false);
        rv.setLoadMoreEnabled(false);
测试发现设置    rv.setLoadMoreEnabled(false);，就会报以上异常

**Comment by jdsjlzx** [comment]
请先初始化LRecyclerViewAdapter！

**Comment by Hellozhongxin** [comment]
嗯好的，感谢！
