### ISSUE TITLE
LRecyclerView嵌套进fragment ,fragment嵌套进ViewPager滑动崩溃

### ISSUE THREAD

**Issue by NikoSoftware** [jdsjlzx/LRecyclerView#109]
你好,LRecyclerView嵌套进fragment ,fragment嵌套进ViewPager滑动崩溃，出现滑动崩溃的现象，版本是1.3.3

**Comment by NikoSoftware** [comment]
java.lang.IllegalStateException: Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@c9b1fb6 was not registered.
                                                       at android.database.Observable.unregisterObserver(Observable.java:69)
                                                       at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6294)
                                                       at com.github.jdsjlzx.recyclerview.LRecyclerView.setAdapter(LRecyclerView.java:137)
                                                       at com.jmw.mangusc.fragment.train.UnpaidFragment.setupViews(UnpaidFragment.java:72)
                                                       at com.jmw.mangusc.fragment.BaseFragment.onViewCreated(BaseFragment.java:66)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1132)
                                                       at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1473)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:791)

**Comment by jdsjlzx** [comment]
你好，最新版本：compile 'com.github.jdsjlzx:LRecyclerView:1.3.4'

初步分析是setAdapter引起的问题，UnpaidFragment.java:72行附近的代码贴一下看看。

**Comment by NikoSoftware** [comment]
mLRecyclerView.setAdapter(mLRecyclerViewAdapter);

**Comment by NikoSoftware** [comment]
mAdapter = new UnpaidOrderAdapter(mContext);

        LRecyclerViewAdapter mLRecyclerViewAdapter = new LRecyclerViewAdapter(mAdapter);
        mLRecyclerView.setLayoutManager(new LinearLayoutManager(mContext));


 72:       mLRecyclerView.setAdapter(mLRecyclerViewAdapter);

**Comment by jdsjlzx** [comment]
LRecyclerViewAdapter mLRecyclerViewAdapter = new LRecyclerViewAdapter(mAdapter);
mLRecyclerView.setAdapter(mLRecyclerViewAdapter);

注意：尽量不要多次调用mLRecyclerView.setAdapter(mLRecyclerViewAdapter)，一次就可以了。

**Comment by NikoSoftware** [comment]
解决了，谢谢
