### ISSUE TITLE
Adapter   移除数据时闪退情况 说索引越界

### ISSUE THREAD

**Issue by NikoSoftware** [jdsjlzx/LRecyclerView#111]
java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                     at com.jmw.mangusc.adapter.baseAdapter.BaseRecyclerViewAdapter.onBindViewHolder(BaseRecyclerViewAdapter.java:60)
                                                     at com.jmw.mangusc.adapter.baseAdapter.BaseRecyclerViewAdapter.onBindViewHolder(BaseRecyclerViewAdapter.java:16)
                                                     at com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter.onBindViewHolder(LRecyclerViewAdapter.java:179)
                                                     at com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter.onBindViewHolder(LRecyclerViewAdapter.java:210)

**Comment by jdsjlzx** [comment]
贴一下代码

**Comment by jdsjlzx** [comment]
参考EndlessLinearLayoutActivity类：
mLRecyclerViewAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                ItemModel item = mDataAdapter.getDataList().get(position);
                AppToast.showShortText(getApplicationContext(), item.title);
                mDataAdapter.remove(position);
            }

        });

注意这里的position，如果你需要在自己的接口里面使用position，需要考虑HeaderView和下拉刷新view，参考：
final int adjPosition = position - (getHeaderViewsCount() + 1);

**Comment by plato1989** [comment]
mLRecyclerViewAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                if (mDataAdapter.getDataList().size() <= position)
                return;
                ItemModel item = mDataAdapter.getDataList().get(position);
                AppToast.showShortText(getApplicationContext(), item.title);
                mDataAdapter.remove(position);
            }
        });

**Comment by jdsjlzx** [comment]
你写的跟我demo中的并没有什么区别，demo中也出这个问题吗？

**Comment by plato1989** [comment]
是的

**Comment by plato1989** [comment]
增加这句  if (mDataAdapter.getDataList().size() <= position)return; 可避免

**Comment by jdsjlzx** [comment]
我验证下，多谢反馈！
