### ISSUE TITLE
下拉刷新后 调用  lRecyclerViewAdapter.notifyDataSetChanged(); 报这个错误

### ISSUE THREAD

**Issue by wooshlele** [jdsjlzx/LRecyclerView#112]
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                       at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5659)
                                                       at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:5766)
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:8321)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3579)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3265)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                       at android.view.View.layout(View.java:15743)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5051)
                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2153)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1907)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:612)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:581)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by jdsjlzx** [comment]
下拉刷新代码贴一下

**Comment by wooshlele** [comment]
少了一句notifyDataSetChanged ()，是我疏忽了，感谢！
