### ISSUE TITLE
LRecyclerView$DataObserver@2572355c was not registered.

### ISSUE THREAD

**Issue by ZhangZhaoGH** [jdsjlzx/LRecyclerView#131]
请问谁遇到这个问题了？我自己测试没问题，但是看友盟反馈的出现这个错误
java.lang.IllegalStateException: Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@2572355c was not registered.
	at android.database.Observable.unregisterObserver(Observable.java:69)
	at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6294)
	at com.github.jdsjlzx.recyclerview.LRecyclerView.setAdapter(LRecyclerView.java:137)
	at com.m1039.drive.ui.fragment.NewHuodongFragment$2.onResponse(NewHuodongFragment.java:219)
	at com.m1039.drive.ui.fragment.NewHuodongFragment$2.onResponse(NewHuodongFragment.java:163)
	at com.zhy.http.okhttp.OkHttpUtils$3.run(OkHttpUtils.java:186)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5413)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by jdsjlzx** [comment]
多测试下，看看有没有问题！请及时反馈！

**Comment by ZhangZhaoGH** [comment]
![image](https://cloud.githubusercontent.com/assets/20332296/24033094/2c193516-0b26-11e7-84c3-786706147656.png)

@jdsjlzx  大神麻烦看下，我自己没测出来，友盟反馈的出现问题

**Comment by jdsjlzx** [comment]
我对此问题进行了优化，等发新版本了再验证下！

**Comment by ZhangZhaoGH** [comment]
辛苦了

**Comment by a48352433** [comment]
'was not registered.'问题没了.但是新版本成这个问题了                                                            `java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{48b22c5 position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}`
