### ISSUE TITLE
在项目中引用不进去，在XMl报错，作者帮我看下

### ISSUE THREAD

**Issue by anhuifix** [jdsjlzx/LRecyclerView#135]
Process: com.caichen.ccplus.ccpuls, PID: 15564
                                                                           android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.github.jdsjlzx.recyclerview.LRecyclerView
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                               at com.caichen.ccplus.ccpuls.ui.shoppingCar.fragment.OrdinaryCarFragment.onCreateView(OrdinaryCarFragment.java:61)

**Comment by anhuifix** [comment]
我都引用了你的那些文件，在xml中使用的时候就这个问题

**Comment by jdsjlzx** [comment]
参考：https://github.com/jdsjlzx/LRecyclerView/blob/master/app/src/main/res/layout/sample_ll_activity.xml

**Comment by Stevenxin** [comment]
本人也遇到了引用XML报错，引用版本ompile 'com.github.jdsjlzx:LRecyclerView:1.4.1'
![qq 20170406161006](https://cloud.githubusercontent.com/assets/12166318/24744185/a7585c58-1ae3-11e7-81c1-f90c633af704.png)
![qq 20170406160952](https://cloud.githubusercontent.com/assets/12166318/24744188/a923db3e-1ae3-11e7-8b9d-a1fcb9c4c5c0.png)

**Comment by guizhongxiaobai** [comment]
我的也是这个问题，也按照作者说的做了，还是报同样的错误，不知道怎么解决
