### ISSUE TITLE
运行在联想手机上报错 无法安装  API是17

### ISSUE THREAD

**Issue by HappySKT** [jdsjlzx/LRecyclerView#144]
java.lang.SecurityException: install operation deny
	at android.os.Parcel.readException(Parcel.java:1425)
	at android.os.Parcel.readException(Parcel.java:1379)
	at android.content.pm.IPackageManager$Stub$Proxy.installPackageWithVerificationAndEncryption(IPackageManager.java:3229)
	at com.android.commands.pm.Pm.runInstall(Pm.java:935)
	at com.android.commands.pm.Pm.run(Pm.java:109)
	at com.android.commands.pm.Pm.main(Pm.java:77)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
	at dalvik.system.NativeStart.main(Native Method)
Killed 

$ adb shell am start -n "com.lzx.demo/com.lzx.demo.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.lzx.demo/com.lzx.demo.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.lzx.demo/.SplashActivity }
Error type 3
Error: Activity class {com.lzx.demo/com.lzx.demo.SplashActivity} does not exist.

Error while Launching activity

**Comment by HappySKT** [comment]
手机重启之后可以正常安装，不知道之前的问题是怎么回事
