### ISSUE TITLE
任何一个有刷新的页面，进去然后返回后就报错

### ISSUE THREAD

**Issue by yudongyy** [jdsjlzx/LRecyclerView#150]
任何一个有刷新的页面，进去然后返回后就报错

**Comment by jdsjlzx** [comment]
有木有log什么的

**Comment by duyangs** [comment]
我也遇到  onDetachedFromWindow()中adapter.unregisterAdapterDataObserver(mDataObserver);
报 java.lang.IllegalStateException: Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@2e67d85 was not registered.

` 13812-13812/com.lzx.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.lzx.demo, PID: 13812
                                                              java.lang.IllegalStateException: Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@2e67d85 was not registered.
                                                                  at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6583)
                                                                  at com.github.jdsjlzx.recyclerview.LRecyclerView.onDetachedFromWindow(LRecyclerView.java:163)
                                                                  at android.view.View.dispatchDetachedFromWindow(View.java:15458)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3227)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
                                                                  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3267)
                                                                  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5893)
                                                                  at android.view.ViewRootImpl.die(ViewRootImpl.java:5870)
                                                                  at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
                                                                  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
                                                                  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
                                                                  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4260)
                                                                  at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1539)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6154)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`
