### ISSUE TITLE
点击任何页面返回报错

### ISSUE THREAD

**Issue by yudongyy** [jdsjlzx/LRecyclerView#153]
java.lang.IllegalStateException: Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@2570a598 was not registered.
                                                                  at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6583)
                                                                  at com.github.jdsjlzx.recyclerview.LRecyclerView.onDetachedFromWindow(LRecyclerView.java:163)
                                                                  at

**Comment by jdsjlzx** [comment]
有木有参考demo？

**Comment by jdsjlzx** [comment]
已经解决问题！请重现拉一下代码！
