### ISSUE TITLE
添加头布局脚布局错误

### ISSUE THREAD

**Issue by liukai2530533** [jdsjlzx/LRecyclerView#154]
在头布局中用FramLayout 控制显示隐藏TextView和WebView就会出错。
TextView cannot be cast to com.github.jdsjlzx.view.SimpleViewSwitcher
  at com.github.jdsjlzx.view.LoadingFooter.setState(LoadingFooter.java:178)                                                           
at com.github.jdsjlzx.view.LoadingFooter.setState(LoadingFooter.java:95)
at com.github.jdsjlzx.view.LoadingFooter.onLoading(LoadingFooter.java:117)
 at com.github.jdsjlzx.recyclerview.LRecyclerView.onScrollStateChanged(LRecyclerView.java:596)

**Comment by liukai2530533** [comment]
只要用WebView就出错。。。

**Comment by liukai2530533** [comment]
拉到底部准备加载更多的时候，崩了。
 java.lang.ClassCastException: android.widget.TextView cannot be cast to com.github.jdsjlzx.view.SimpleViewSwitcher
 at com.github.jdsjlzx.view.LoadingFooter.setState(LoadingFooter.java:179)
 at com.github.jdsjlzx.view.LoadingFooter.setState(LoadingFooter.java:95)
 at com.github.jdsjlzx.view.LoadingFooter.onLoading(LoadingFooter.java:117)
完全是不明所以。只要加入webview就这样  不管是xml布局还是java创建 都一样noscrollwebview也不行

**Comment by jdsjlzx** [comment]
TextView cannot be cast to com.github.jdsjlzx.view.SimpleViewSwitcher 根据这个log再分析下吧！定义的id不要跟library中的一样！

**Comment by jdsjlzx** [comment]
详见demo：https://github.com/jdsjlzx/LRecyclerView/tree/master/app

**Comment by liukai2530533** [comment]
不是id的问题 好像是webview不能写在xml中。我再java代码手动添加并设置宽高后解决

**Comment by liukai2530533** [comment]
希望作者可以开放LRecyclerAdapter。最好是lrecycler.getAdapter获取到LRecyclerAdapter

**Comment by jdsjlzx** [comment]
lrecycler.getAdapter获取到的就是LRecyclerViewAdapter
