### ISSUE TITLE
快速上拉加载更多

### ISSUE THREAD

**Issue by fengluoye2012** [jdsjlzx/LRecyclerView#201]
Added View has RecyclerView as parent but view is not a real child

**Comment by lieying001** [comment]
我的也出现这个问题了，Added View has RecyclerView as parent but view is not a real child.

at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7871)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                          at android.view.View.measure(View.java:18796)

**Comment by imexception** [comment]
问题很严重：Added View has RecyclerView as parent but view is not a real child。

at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7871)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                          at android.view.View.measure(View.java:18796)

**Comment by xinyangcuncun** [comment]
@fengluoye2012  你解决了吗
