### ISSUE TITLE
配合BaseRecyclerViewAdapterHelper使用时报类转换异常该怎么解决

### ISSUE THREAD

**Issue by singlenoah** [jdsjlzx/LRecyclerView#233]
`  java.lang.ClassCastException: com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter$ViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolder
                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onViewAttachedToWindow(BaseQuickAdapter.java:68)
                                                     at com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter.onViewAttachedToWindow(LRecyclerViewAdapter.java:315)`

**Comment by jdsjlzx** [comment]
BaseRecyclerViewAdapterHelper库与本框架功能有重叠部分，且实现方式不一样，结合使用会出现冲突！
