### ISSUE TITLE
PullScrollview 的子孩子中包含recycerview时setLayout方法中 group.removeView(this); 报空指针

### ISSUE THREAD

**Issue by liu1912009189** [jdsjlzx/LRecyclerView#264]
01-16 16:37:13.683 10432-10432/com.lzx.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.lzx.demo, PID: 10432
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.GapWorker.remove(android.support.v7.widget.RecyclerView)' on a null object reference
                                                                  at android.support.v7.widget.RecyclerView.onDetachedFromWindow(RecyclerView.java:2534)
                                                                  at android.view.View.dispatchDetachedFromWindow(View.java:14665)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3077)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3069)
                                                                  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3069)
                                                                  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4622)
                                                                  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4595)
                                                                  at android.view.ViewGroup.removeView(ViewGroup.java:4526)
                                                                  at com.lzx.demo.view.PullScrollView.setLayout(PullScrollView.java:67)
                                                                  at com.lzx.demo.view.PullScrollView.onAttachedToWindow(PullScrollView.java:277) 这是你的源代码，将recyclerview换成listview又可以，这个bug很尴尬呢

**Comment by jdsjlzx** [comment]
已经解决，详见demo！
