### ISSUE TITLE
遇到一个报错

### ISSUE THREAD

**Issue by MelvinCen** [jdsjlzx/LRecyclerView#270]
在fragment中的根布局使用pullScrollview，运行崩溃 错误：
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4741)
                                                                         at android.view.ViewGroup.removeViewAt(ViewGroup.java:4704)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1540)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                         at android.os.Handler.handleCallback(Handler.java:754)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:163)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by MelvinCen** [comment]
楼主知道吗？谁遇到过这个问题？

**Comment by MelvinCen** [comment]
在scrollview内部是有点击的按钮的

**Comment by jdsjlzx** [comment]
这个没有发现是pullScrollview的问题呢？再追踪下log！

**Comment by MelvinCen** [comment]
@jdsjlzx 在pullscrollview外部套一个framlayout（根布局）就不崩溃了，但是在点击区域没有滑动事件= =

**Comment by MelvinCen** [comment]
已解决，scrollview的子布局不满一屏幕，里面的子控件的点击按钮只响应了点击，没有响应scrollview的滑动，用代码把子空间的高度设置为屏幕高度。
参考博客：http://blog.csdn.net/u012591761/article/details/53511935
