### ISSUE TITLE
androidX

### ISSUE THREAD

**Issue by Alwaysm** [jdsjlzx/LRecyclerView#328]
会适配androidx的版本么？

**Comment by wangkai147** [comment]
1

**Comment by Cuixiaoyang123** [comment]
我升级了AndroidX ，一滑动就会crash

Caused by: java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002) 
        at $Proxy29.dispatchTouchEvent(Unknown Source)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.taobao.monitor.impl.data.activity.WindowCallbackProxy.invoke(WindowCallbackProxy.java:48) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy31.dispatchTouchEvent(Unknown Source) 
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)

**Comment by Cuixiaoyang123** [comment]
请问是不是咱们的LRecyclerView和AndroidX不兼容呀？？

**Comment by wangkai147** [comment]
换个库吧兄弟，早不维护了
