### ISSUE TITLE
Called attach on a child which is not detached: ViewHolder...

### ISSUE THREAD

**Issue by qiu1992** [jdsjlzx/LRecyclerView#36]
这个问题，一般在发生在上拉加载更多，有时候下拉刷新也会。关于这个问题，发现你在EndlessLinearLayoutActivity.java，87行中有加这么一句代码：mLRecyclerViewAdapter.notifyDataSetChanged();
但是这样并不能解决问题。具体原因没有去研究。说说我的解决方法（使用了项目中的：ListBaseAdapter）。ListBaseAdapter中的setDataList、addAll、remove、clear方法中，都有notifyxxxx方法，经过试验。有两种解决方法：
（1）删除上述方法里面的notifyxxxx方法。在调用上述方法之后，紧接着调用xxxadapter.notifyDataSetChanged方法；
（2）可以保留上述方法里面的notifyxxxx方法，在调用上述方法之后，紧接着调用xxxadapter.notifyDataSetChanged方法。考虑到notify两次，所以不建议。

下面是具体的错误信息：
java.lang.IllegalArgumentException
Called attach on a child which is not detached: ViewHolder{742af16 position=40 id=-1, oldPos=-1, pLpos:-1}

1 android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:692)
2 android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
3 android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1178)
4 android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3535)
5 android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:456)
6 android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:246)
7 android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3385)
8 android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3135)
9 android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
10 android.view.View.layout(View.java:15718)
11 android.view.ViewGroup.layout(ViewGroup.java:5039)
12 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
13 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
14 android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
15 android.view.View.layout(View.java:15718)
16 android.view.ViewGroup.layout(ViewGroup.java:5039)
17 android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
18 android.widget.FrameLayout.onLayout(FrameLayout.java:514)
19 android.view.View.layout(View.java:15718)
20 android.view.ViewGroup.layout(ViewGroup.java:5039)
21 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
22 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
23 android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
24 android.view.View.layout(View.java:15718)
25 android.view.ViewGroup.layout(ViewGroup.java:5039)
26 android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
27 android.widget.FrameLayout.onLayout(FrameLayout.java:514)
28 android.view.View.layout(View.java:15718)
29 android.view.ViewGroup.layout(ViewGroup.java:5039)
30 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
31 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
32 android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
33 android.view.View.layout(View.java:15718)
34 android.view.ViewGroup.layout(ViewGroup.java:5039)
35 android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
36 android.widget.FrameLayout.onLayout(FrameLayout.java:514)
37 android.view.View.layout(View.java:15718)
38 android.view.ViewGroup.layout(ViewGroup.java:5039)
39 android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2127)
40 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1884)
41 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1102)
42 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5930)
43 android.view.Choreographer$CallbackRecord.run(Choreographer.java:769)
44 android.view.Choreographer.doCallbacks(Choreographer.java:582)
45 android.view.Choreographer.doFrame(Choreographer.java:552)
46 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:755)
47 android.os.Handler.handleCallback(Handler.java:739)
48 android.os.Handler.dispatchMessage(Handler.java:95)
49 android.os.Looper.loop(Looper.java:135)
50 android.app.ActivityThread.main(ActivityThread.java:5298)
51 java.lang.reflect.Method.invoke(Native Method)
52 java.lang.reflect.Method.invoke(Method.java:372)
53 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
54 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by jdsjlzx** [comment]
现在使用还有这个问题吗？

**Comment by SaltedFish999** [comment]
called detach on an already detached child ViewHolder

您好，我遇到了这个问题，这个问题出现的情况是我当前界面的 LRecyclerView 添加了 HeaderView 之后跳转到下一个有两个 HeaderView（一个不会出现这种情况） 的 Activity 就会出现这种情况， 请问如何解决呢？

具体错误信息：
java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{154c4fd1 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
    at android.support.v7.widget.RecyclerView$5.detachViewFromParent(RecyclerView.java:710)
    at android.support.v7.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
    at android.support.v7.widget.RecyclerView$LayoutManager.detachViewInternal
(RecyclerView.java:7301)
    at android.support.v7.widget.RecyclerView$LayoutManager.detachViewAt
(RecyclerView.java:7294)
    at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView
(RecyclerView.java:7699)
    at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews
(RecyclerView.java:7682)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren
(LinearLayoutManager.java:546)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
    at android.view.View.layout(View.java:16112)
    at android.view.ViewGroup.layout(ViewGroup.java:5185)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2548)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2233)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1330)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6705)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
    at android.view.Choreographer.doCallbacks(Choreographer.java:603)
    at android.view.Choreographer.doFrame(Choreographer.java:572)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:192)
    at android.app.ActivityThread.main(ActivityThread.java:5865)
    at java.lang.reflect.Method.invoke(Native Meth

**Comment by jdsjlzx** [comment]
此问题常见于索引异常，请使用最新版本验证下！

**Comment by supperyan** [comment]
不会的都说是版本问题！（/斜眼笑）
